// vue/src/components/link/LinkItem.vue
<template>
  <RouterLink :to="item.link" :class="className">{{ item.title }}</RouterLink>
</template>

<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { TypeLink } from '@/types/TypeLink'
import { defineProps } from 'vue'

interface LinkItemProps {
  item: TypeLink
  className?: string
}

const props = defineProps<LinkItemProps>()
</script>

// react/src/components/link/LinkItem.tsx
import { FC } from "react"
import { Link } from "react-router-dom"
import { TypeLink } from "../../types/TypeLink"

interface LinkItemProps {
    item: TypeLink,
    className?: string
}

export const LinkItem: FC<LinkItemProps> = ({item, className}) => {
    return(
        <Link key = {item.title} to = {item.link} className={className}>
            {item.title}
        </Link>
    )
}
