// preact-web/src/uikit/authTitle/AuthTitle.tsx
import { FC } from "preact/compat";
import { Link } from "react-router-dom";
import classNames from "classnames";

import style from "./AuthTitle.module.scss";


interface AuthTitleProps {
    title: string;
    path: string;
    linkText: string;
    className?: string;
}

export const AuthTitle:FC<AuthTitleProps> = ({className, title, path, linkText}) =>{
    return(
        <div className={classNames(style.wrapper, className)}>
            <h2>{title}</h2>
            <p>
                <Link to = {path} className={style.link}>{linkText}</Link>
            </p>
        </div>
    )
}

// vue/src/uikit/authTitle/AuthTitle.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import { RouterLink } from 'vue-router'
import styles from './AuthTitle.module.scss'

interface AuthTitleProps {
  title: string
  path: string
  linkText: string
}

const props = defineProps<AuthTitleProps>()
</script>

<template>
  <div :class="styles.wrapper">
    <h2>{{ title }}</h2>
    <p>
      <RouterLink :to="path" :class="styles.link">{{ linkText }}</RouterLink>
    </p>
  </div>
</template>
