// react/src/components/nav/NavMenu.tsx
import { FC } from "react";
import { NavLink} from "react-router-dom";
import classNames from "classnames";
import { IS_MOBILE } from "../../Constants";
import CompetitionIcon from "assets/icons/competitions.svg?react";
import LkIcon from "assets/icons/lk.svg?react";

import styles from './NavMenu.module.scss'

export const NavMenu: FC = () => {

    return(
        <nav className={styles.nav}>
            <div className={classNames(!IS_MOBILE && 'container',styles.nav__container)}>
                <div className={styles.nav__list}>
                    <NavLink 
                        to = "/" 
                        end 
                        className = {({ isActive }) => !isActive ? styles.nav__link : classNames(styles.nav__link, styles.nav__link_select) }
                    >
                        {IS_MOBILE && <CompetitionIcon key = {'competition'} className={styles.nav__icon} width={30} height={30} fill="#4F4F4F" />}
                        <span>Конкурсы</span>
                    </NavLink>
                    
                    {IS_MOBILE && <NavLink 
                        to = "account" 
                        className = {({ isActive })=> !isActive ? styles.nav__link : classNames(styles.nav__link, styles.nav__link_select)} >
                        <LkIcon className={styles.nav__icon} width={30} height={30} fill="#4F4F4F" />
                        <span>кабинет</span>
                    </NavLink>}
                </div>
                { !IS_MOBILE && 
                    <NavLink to = "account" className={styles.nav__lk}>
                        <LkIcon width={50} height={50} />
                    </NavLink>}
            </div>
        </nav>
    )
}

// vue/src/components/nav/NavMenu.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import IconCompetitions from '@/components/icons/IconCompetitions.vue'
import IconLk from '@/components/icons/IconLk.vue'
import constants from '@/utils/ts/constants'
import styles from './NavMenu.module.scss'
</script>

<template>
  <nav :class="styles.nav">
    <div :class="[{ ['container']: !constants.IS_MOBILE }, styles.nav__container]">
      <div :class="styles.nav__list">
        <RouterLink to="/" :class="[styles.nav__link]">
          <IconCompetitions
            v-if="constants.IS_MOBILE"
            :class="styles.nav__icon"
            :width="30"
            :height="30"
            :fill="'#4F4F4F'"
          />
          <span>Конкурсы</span>
        </RouterLink>

        <RouterLink v-if="constants.IS_MOBILE" to="/account" :class="[styles.nav__link]">
          <IconLk :class="styles.nav__icon" :width="30" :height="30" :fill="'#4F4F4F'" />
          <span>кабинет</span>
        </RouterLink>
      </div>
      <RouterLink v-if="!constants.IS_MOBILE" to="/account" :class="styles.nav__lk">
        <IconLk :width="50" :height="50" />
      </RouterLink>
    </div>
  </nav>
</template>

<style scoped>
.router-link-active {
  transition: background-color 0.3s linear;
  background-color: #ffffe0;

  @media (max-width: 1024px) {
    background-color: inherit;
    color: #ff6b00;

    svg * {
      color: #ff6b00;
      fill: #ff6b00;
    }
  }
}
</style>
