// react/src/uikit/input/InputControl.tsx
import { FC, InputHTMLAttributes, forwardRef } from "react";
import classNames from "classnames";
import style from './InputControl.module.scss'

interface InputControlProps extends InputHTMLAttributes<HTMLInputElement> {
    label?: string,
    error?: string,
    classNameContainer?: string;
}

export const InputControl:FC<InputControlProps> = forwardRef<HTMLInputElement, InputControlProps>((props, ref)  => {
    
    const {label, error, classNameContainer, ...inputProps} = props
    
    return(
        <div className={classNames(
            classNameContainer,
            style.inputContainer
        )}>
            <input
                className={classNames(
                    props.className,
                    style.input
                )} 
                ref={ref}
                {...inputProps} 
            />
            <label className={style.label} htmlFor={props.id || props.name}> {label}</label>
            <div className='error-text'>{error}</div>
        </div>
    )
})

// vue/src/uikit/inputControl/InputControl.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import styles from './InputControl.module.scss'

interface InputControlProps {
  label: string
  placeholder?: string
  error?: string
  modelValue?: string
  type: string
}

const props = defineProps<InputControlProps>()

const emit = defineEmits(['update:modelValue'])

function change(event: Event) {
  const el = event.target as HTMLInputElement
  emit('update:modelValue', el.value)
}

let id = 'input-' + Math.random()
</script>

<template>
  <div :class="styles.inputContainer">
    <input
      :type="type"
      :id="id"
      :class="styles.input"
      :placeholder="placeholder || ''"
      @input="change"
      :modelValue="modelValue"
    />
    <label :for="id" :class="styles.label">{{ label }}</label>
    <div v-if="!!error" class="error-text">{{ error }}</div>
  </div>
</template>
