// vue/src/uikit/linkToMain/LinkToMain.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import IconArrowLeft from '@/components/icons/IconArrowLeft.vue'
import styles from './LinkToMain.module.scss'
</script>

<template>
  <RouterLink to="/" :class="styles.toMain">
    <IconArrowLeft width="16" height="16" fill="#FF6B00" />
    Главная
  </RouterLink>
</template>

// preact-web/src/uikit/linkToMain/LinkToMain.tsx
import { Link } from "react-router-dom";
import ArrowLeft from "assets/icons/arrow-left.svg?react";

import style from "./LinkToMain.module.scss";

export const LinkToMain = () => {
  return (
    <Link to="/" className={style.toMain}>
      <ArrowLeft width={16} height={16} fill="#FF6B00" /> Главная
    </Link>
  );
};
